/** @type {import('tailwindcss').Config} */
module.exports = {
  important: false, // Explicitly disable !important to allow consumer overrides
  content: [
    './src/**/*.{ts,tsx,html}',
    './playground/**/*.{html,js}',
    './.storybook/**/*.{js,ts,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--ds-color-primary-50)',
          100: 'var(--ds-color-primary-100)',
          200: 'var(--ds-color-primary-200)',
          300: 'var(--ds-color-primary-300)',
          400: 'var(--ds-color-primary-400)',
          500: 'var(--ds-color-primary-500)',
          600: 'var(--ds-color-primary-600)',
          700: 'var(--ds-color-primary-700)',
          800: 'var(--ds-color-primary-800)',
          900: 'var(--ds-color-primary-900)',
          950: 'var(--ds-color-primary-950)',
        },
        secondary: {
          50: 'var(--ds-color-secondary-50)',
          100: 'var(--ds-color-secondary-100)',
          200: 'var(--ds-color-secondary-200)',
          300: 'var(--ds-color-secondary-300)',
          400: 'var(--ds-color-secondary-400)',
          500: 'var(--ds-color-secondary-500)',
          600: 'var(--ds-color-secondary-600)',
          700: 'var(--ds-color-secondary-700)',
          800: 'var(--ds-color-secondary-800)',
          900: 'var(--ds-color-secondary-900)',
          950: 'var(--ds-color-secondary-950)',
        },
        success: {
          50: 'var(--ds-color-success-50)',
          100: 'var(--ds-color-success-100)',
          200: 'var(--ds-color-success-200)',
          300: 'var(--ds-color-success-300)',
          400: 'var(--ds-color-success-400)',
          500: 'var(--ds-color-success-500)',
          600: 'var(--ds-color-success-600)',
          700: 'var(--ds-color-success-700)',
          800: 'var(--ds-color-success-800)',
          900: 'var(--ds-color-success-900)',
        },
        warning: {
          50: 'var(--ds-color-warning-50)',
          100: 'var(--ds-color-warning-100)',
          200: 'var(--ds-color-warning-200)',
          300: 'var(--ds-color-warning-300)',
          400: 'var(--ds-color-warning-400)',
          500: 'var(--ds-color-warning-500)',
          600: 'var(--ds-color-warning-600)',
          700: 'var(--ds-color-warning-700)',
          800: 'var(--ds-color-warning-800)',
          900: 'var(--ds-color-warning-900)',
        },
        error: {
          50: 'var(--ds-color-error-50)',
          100: 'var(--ds-color-error-100)',
          200: 'var(--ds-color-error-200)',
          300: 'var(--ds-color-error-300)',
          400: 'var(--ds-color-error-400)',
          500: 'var(--ds-color-error-500)',
          600: 'var(--ds-color-error-600)',
          700: 'var(--ds-color-error-700)',
          800: 'var(--ds-color-error-800)',
          900: 'var(--ds-color-error-900)',
        },
        neutral: {
          50: 'var(--ds-color-neutral-50)',
          100: 'var(--ds-color-neutral-100)',
          200: 'var(--ds-color-neutral-200)',
          300: 'var(--ds-color-neutral-300)',
          400: 'var(--ds-color-neutral-400)',
          500: 'var(--ds-color-neutral-500)',
          600: 'var(--ds-color-neutral-600)',
          700: 'var(--ds-color-neutral-700)',
          800: 'var(--ds-color-neutral-800)',
          900: 'var(--ds-color-neutral-900)',
          950: 'var(--ds-color-neutral-950)',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'Monaco',
          'Cascadia Code',
          'Segoe UI Mono',
          'Roboto Mono',
          'monospace',
        ],
      },
      spacing: {
        'ds-0': 'var(--ds-spacing-0)',
        'ds-px': 'var(--ds-spacing-px)',
        'ds-0.5': 'var(--ds-spacing-0-5)',
        'ds-1': 'var(--ds-spacing-1)',
        'ds-1.5': 'var(--ds-spacing-1-5)',
        'ds-2': 'var(--ds-spacing-2)',
        'ds-2.5': 'var(--ds-spacing-2-5)',
        'ds-3': 'var(--ds-spacing-3)',
        'ds-3.5': 'var(--ds-spacing-3-5)',
        'ds-4': 'var(--ds-spacing-4)',
        'ds-5': 'var(--ds-spacing-5)',
        'ds-6': 'var(--ds-spacing-6)',
        'ds-8': 'var(--ds-spacing-8)',
        'ds-10': 'var(--ds-spacing-10)',
        'ds-12': 'var(--ds-spacing-12)',
        'ds-16': 'var(--ds-spacing-16)',
        'ds-20': 'var(--ds-spacing-20)',
        'ds-24': 'var(--ds-spacing-24)',
        'ds-32': 'var(--ds-spacing-32)',
      },
    },
  },
  plugins: [],
};
