/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonVariant } from "./components/button/button";
import { InputSize, InputType } from "./components/input/input";
export { ButtonSize, ButtonVariant } from "./components/button/button";
export { InputSize, InputType } from "./components/input/input";
export namespace Components {
    interface DsButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the button should take full width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Whether the button is in loading state
          * @default false
         */
        "loading": boolean;
        /**
          * The button size
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * Button type attribute
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * The button variant
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface DsInput {
        /**
          * Input autocomplete attribute
          * @default ''
         */
        "autocomplete": string;
        /**
          * Whether the input is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message to display
          * @default ''
         */
        "error": string;
        /**
          * Whether the input should take full width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Helper text to display
          * @default ''
         */
        "helperText": string;
        /**
          * The input label
          * @default ''
         */
        "label": string;
        /**
          * Maximum length of input
         */
        "maxlength": number;
        /**
          * Minimum length of input
         */
        "minlength": number;
        /**
          * Input name attribute
          * @default ''
         */
        "name": string;
        /**
          * The input placeholder
          * @default ''
         */
        "placeholder": string;
        /**
          * Whether the input is readonly
          * @default false
         */
        "readonly": boolean;
        /**
          * Whether the input is required
          * @default false
         */
        "required": boolean;
        /**
          * The input size
          * @default 'md'
         */
        "size": InputSize;
        /**
          * The input type
          * @default 'text'
         */
        "type": InputType;
        /**
          * The input value
          * @default ''
         */
        "value": string;
    }
    interface DsSpinner {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface DsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsInputElement;
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsInputElementEventMap {
        "dsInput": string;
        "dsFocus": void;
        "dsBlur": void;
    }
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsInputElementEventMap>(type: K, listener: (this: HTMLDsInputElement, ev: DsInputCustomEvent<HTMLDsInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsInputElementEventMap>(type: K, listener: (this: HTMLDsInputElement, ev: DsInputCustomEvent<HTMLDsInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLDsSpinnerElement extends Components.DsSpinner, HTMLStencilElement {
    }
    var HTMLDsSpinnerElement: {
        prototype: HTMLDsSpinnerElement;
        new (): HTMLDsSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-input": HTMLDsInputElement;
        "ds-spinner": HTMLDsSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the button should take full width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Whether the button is in loading state
          * @default false
         */
        "loading"?: boolean;
        /**
          * The button size
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * Button type attribute
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * The button variant
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface DsInput {
        /**
          * Input autocomplete attribute
          * @default ''
         */
        "autocomplete"?: string;
        /**
          * Whether the input is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message to display
          * @default ''
         */
        "error"?: string;
        /**
          * Whether the input should take full width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Helper text to display
          * @default ''
         */
        "helperText"?: string;
        /**
          * The input label
          * @default ''
         */
        "label"?: string;
        /**
          * Maximum length of input
         */
        "maxlength"?: number;
        /**
          * Minimum length of input
         */
        "minlength"?: number;
        /**
          * Input name attribute
          * @default ''
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus
         */
        "onDsBlur"?: (event: DsInputCustomEvent<void>) => void;
        /**
          * Emitted when the input is focused
         */
        "onDsFocus"?: (event: DsInputCustomEvent<void>) => void;
        /**
          * Emitted when the input value changes
         */
        "onDsInput"?: (event: DsInputCustomEvent<string>) => void;
        /**
          * The input placeholder
          * @default ''
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required
          * @default false
         */
        "required"?: boolean;
        /**
          * The input size
          * @default 'md'
         */
        "size"?: InputSize;
        /**
          * The input type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * The input value
          * @default ''
         */
        "value"?: string;
    }
    interface DsSpinner {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-input": DsInput;
        "ds-spinner": DsSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-input": LocalJSX.DsInput & JSXBase.HTMLAttributes<HTMLDsInputElement>;
            "ds-spinner": LocalJSX.DsSpinner & JSXBase.HTMLAttributes<HTMLDsSpinnerElement>;
        }
    }
}
