/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/button/button";
import { InputSize, InputType } from "./components/input/input";
import { TypographyColor, TypographyVariant } from "./components/typography/typography";
export { ButtonSize, ButtonType, ButtonVariant } from "./components/button/button";
export { InputSize, InputType } from "./components/input/input";
export { TypographyColor, TypographyVariant } from "./components/typography/typography";
export namespace Components {
    interface DsButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * @default 'button'
         */
        "type": ButtonType;
        /**
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface DsInput {
        /**
          * @default ''
         */
        "autocomplete": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * @default ''
         */
        "label": string;
        "maxlength": number;
        "minlength": number;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": InputSize;
        /**
          * @default 'text'
         */
        "type": InputType;
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsSpinner {
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface DsTypography {
        /**
          * @default 'left'
         */
        "align": 'left' | 'center' | 'right';
        /**
          * @default 'primary'
         */
        "color": TypographyColor;
        /**
          * @default 'body'
         */
        "variant": TypographyVariant;
        /**
          * @default 'normal'
         */
        "weight": 'normal' | 'medium' | 'semibold' | 'bold';
    }
}
export interface DsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsInputElement;
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsInputElementEventMap {
        "dsInput": string;
        "dsFocus": void;
        "dsBlur": void;
    }
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsInputElementEventMap>(type: K, listener: (this: HTMLDsInputElement, ev: DsInputCustomEvent<HTMLDsInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsInputElementEventMap>(type: K, listener: (this: HTMLDsInputElement, ev: DsInputCustomEvent<HTMLDsInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLDsSpinnerElement extends Components.DsSpinner, HTMLStencilElement {
    }
    var HTMLDsSpinnerElement: {
        prototype: HTMLDsSpinnerElement;
        new (): HTMLDsSpinnerElement;
    };
    interface HTMLDsTypographyElement extends Components.DsTypography, HTMLStencilElement {
    }
    var HTMLDsTypographyElement: {
        prototype: HTMLDsTypographyElement;
        new (): HTMLDsTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-input": HTMLDsInputElement;
        "ds-spinner": HTMLDsSpinnerElement;
        "ds-typography": HTMLDsTypographyElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * @default 'button'
         */
        "type"?: ButtonType;
        /**
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface DsInput {
        /**
          * @default ''
         */
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        "maxlength"?: number;
        "minlength"?: number;
        /**
          * @default ''
         */
        "name"?: string;
        "onDsBlur"?: (event: DsInputCustomEvent<void>) => void;
        "onDsFocus"?: (event: DsInputCustomEvent<void>) => void;
        "onDsInput"?: (event: DsInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: InputSize;
        /**
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsSpinner {
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface DsTypography {
        /**
          * @default 'left'
         */
        "align"?: 'left' | 'center' | 'right';
        /**
          * @default 'primary'
         */
        "color"?: TypographyColor;
        /**
          * @default 'body'
         */
        "variant"?: TypographyVariant;
        /**
          * @default 'normal'
         */
        "weight"?: 'normal' | 'medium' | 'semibold' | 'bold';
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-input": DsInput;
        "ds-spinner": DsSpinner;
        "ds-typography": DsTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-input": LocalJSX.DsInput & JSXBase.HTMLAttributes<HTMLDsInputElement>;
            "ds-spinner": LocalJSX.DsSpinner & JSXBase.HTMLAttributes<HTMLDsSpinnerElement>;
            "ds-typography": LocalJSX.DsTypography & JSXBase.HTMLAttributes<HTMLDsTypographyElement>;
        }
    }
}
